#!/usr/bin/env bash
PACKAGE="${1:-$(ff apps-sdk default-package)}"
RELEASE_TYPE="${2:-$(ff apps-sdk default-release-type)}"
SCRIPT="${3:-}"
cd "$(ff apps-sdk build-path-to-built-package "$PACKAGE" "$RELEASE_TYPE")"
eval "$SCRIPT"