#!/usr/bin/env bash
# shellcheck source=/dev/null
source "${FF_SCRIPT_HOME}/.lib/devbox.sh"
devbox_prepend_if_omitted "$0" "$@"

command=cursor
canva_number=
repo=

for arg in "${@:2}"; do
  [[ -z "$arg" ]] && continue
  if [[ "$arg" =~ ^command:(.+)$ ]]; then
    command="${BASH_REMATCH[1]}"
  elif [[ "$arg" =~ ^repo:(.+)$ ]]; then
    repo="${BASH_REMATCH[1]}"
  elif [[ "$arg" =~ ^[0-9]+$ ]]; then
    canva_number=$arg
  fi
done

repo=${repo:-canva$canva_number}

$command --remote ssh-remote+coder-vscode.coder.canva-internal.com--frankief--$1.main /home/coder/work/$repo
