#!/usr/bin/env bash
# shellcheck source=/dev/null
source "${FF_SCRIPT_HOME}/.lib/devbox.sh"
devbox_prepend_if_omitted "$0" "$@"

if [[ $# -eq 0 ]]; then
  echo "usage: ff devbox wake <devbox> [<devbox>...]" >&2
  exit 1
fi
ff devbox ff "$@" -- devbox resetup
