#!/usr/bin/env bash
# Call start with app_sandbox_editor added to the -e list
env="${1:-staging}"
[[ $# -ge 1 ]] && shift
# Default to editor as page when nothing provided
pages=("${@:-editor}")
ff c start "$env" app_sandbox_editor "${pages[@]}"
