name: autobump
on:
  push:
     branches:
       - master
  pull_request:
     types: [opened, labeled]
     branches:
       - master
jobs:
  autobump:
    name: autobump
    runs-on: ubuntu-20.04
    steps:
      - name: Auto Bump Check
        id: autobump-check
        uses: docker://francescoferraioli/autobump-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PACKAGES_IN_REPO: "default|;"
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto Bump Run
        uses: francescoferraioli/autobump@v4.0.2
        with:
          AUTOBUMP_RUN: ${{ steps.autobump-check.outputs.AUTOBUMP_RUN }}