name: Enforce autobump label

on:
  pull_request:
     types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  enforce-autobump-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: 'autobump-major,autobump-minor,autobump-patch,no-autobump'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Bump package version before merging using an autobump label ['autobump-major', 'autobump-minor', 'autobump-patch', 'no-autobump']"
  